# Постанова Задачі №1 
*Виконати набір вправ. Всі завдання виконати 2 способами:*
* з використанням універсальних функцій бібліотеки NumPy;
* за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо)

*Для обох випадків підрахувати час виконання скрипту та зробити висновки.*
## Вправа 3
*Вводяться 4 числа n, m, r, c. Вивести масив розміру n×m, в якому в кожному рядку з номером r і в кожному стовпчику з номером c стоять 0, а інші елементи дорівнюють 1.*

In [2]: task_3()

6 7 2 3
      
### Код програми (виконання завдання першим способом):

In [1]:
import numpy as np

def task3_numpy(n, m, r, c):
    # Створення масиву розміру n×m, в якому всі елементи рівні 1
    result_array = np.ones((n, m), dtype=int)

    # Заміна елементів у вибраних рядках та стовпцях на 0
    result_array[r, :] = 0
    result_array[:, c] = 0

    return result_array

# Виклик функції та вивід результатів
n, m, r, c = 6, 7, 2, 3
result_numpy = task3_numpy(n, m, r, c)
result_numpy

array([[1, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 1, 1]])

In [3]:
%timeit task3_numpy(n, m, r, c)

3.79 µs ± 190 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Код програми (виконання завдання другим способом):

In [4]:
def task3_iterative(n, m, r, c):
    # Створення масиву розміру n×m, в якому всі елементи рівні 1
    result_array = [[1] * m for _ in range(n)]

    # Заміна елементів у вибраних рядках та стовпцях на 0
    result_array[r] = [0] * m
    for row in result_array:
        row[c] = 0

    return result_array

# Виклик функції та вивід результатів
result_iterative = task3_iterative(n, m, r, c)
result_iterative

[[1, 1, 1, 0, 1, 1, 1],
 [1, 1, 1, 0, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 0],
 [1, 1, 1, 0, 1, 1, 1],
 [1, 1, 1, 0, 1, 1, 1],
 [1, 1, 1, 0, 1, 1, 1]]

In [5]:
%timeit task3_iterative(n, m, r, c)

2.48 µs ± 229 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## Вправа 5
*Вводиться число n. Вивести масив розміру n×n, в якому в рядках з парними індексами стоять 1, а в інших – 0.*

In [2]:   task_5() 
                
Out[2]: 5   
| 1 | 1 | 1 | 1 | 1 | 
|---|---|---|---|---|
| 0 | 0 | 0 | 0 | 0 |       
| 1 | 1 | 1 | 1 | 1 |         
| 0 | 0 | 0 | 0 | 0 |       
| 1 | 1 | 1 | 1 | 1 |
      
      
### Код програми (виконання завдання першим способом):

In [6]:
import numpy as np
import time

def task5_numpy(n):
    start_time = time.time()

    # Створення масиву розміру n×n, в якому в рядках з парними індексами стоять 1, а в інших – 0
    array = np.zeros((n, n), dtype=int)
    array[::2, :] = 1

    end_time = time.time()
    execution_time = end_time - start_time

    return array, execution_time

# Приклад виклику функції:
n = int(input("Введіть значення n: "))
# n = 5
result_numpy, time_numpy = task5_numpy(n)
result_numpy, time_numpy

Введіть значення n: 5


(array([[1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1]]),
 0.0)

### Код програми (виконання завдання другим способом):

In [7]:
def task_5_iter(n):
    arr = []
    for i in range(n):
        row = []
        for j in range(n):
            if i % 2 == 0:
                row.append(1)
            else:
                row.append(0)
        arr.append(row)
    return arr

def print_matrix(arr):
    for row in arr:
        print(" ".join(map(str, row)))

def task_5(n):
    start = time.time()
    arr = task_5_iter(n)
    end = time.time()
    print(f"Час виконання скрипту з використанням ітеративних конструкцій: {end - start:.2f} секунд")
    print_matrix(arr)

task_5(n=5)

Час виконання скрипту з використанням ітеративних конструкцій: 0.00 секунд
1 1 1 1 1
0 0 0 0 0
1 1 1 1 1
0 0 0 0 0
1 1 1 1 1


## Вправа 7
*З клавіатури вводиться масив. Замінити всі нульові елементи на –1.*

In [2]:   task_7() 
| 3 | 4 | 0 | 6 | 5 | 0 | 3 | 0 | 4 | 
|---|---|---|---|---|---|---|---|---|

Out[2]: 
| 3 | 4 | -1 | 6 | 5 | -1 | 3 | -1 | 4 | 
|---|---|---|---|---|---|---|---|---|
      
### Код програми (виконання завдання першим та другим способами):

In [8]:
from IPython.display import display, Markdown

def task_7_numpy(arr):
    start_time = time.time()
    np_arr = np.array(arr)
    np_arr[np_arr == 0] = -1
    end_time = time.time()
    print("NumPy execution time:", end_time - start_time)
    return np_arr

def task_7_iterative(arr):
    start_time = time.time()
    result_iterative = [-1 if x == 0 else x for x in arr]
    end_time = time.time()
    print("Iterative execution time:", end_time - start_time)
    return result_iterative

# Введення масиву з клавіатури
arr = list(map(int, input("Введіть елементи масиву через пробіл: ").split()))

# Виклик функцій
%time result_numpy = task_7_numpy(arr)

%time result_iterative = task_7_iterative(arr)

# Вивід результатів
display(Markdown(f"**NumPy result:** {result_numpy}"))
display(Markdown(f"**Iterative result:** {result_iterative}"))

Введіть елементи масиву через пробіл: 3 4 0 6 5 0 3 0 4 
NumPy execution time: 0.0009951591491699219
CPU times: total: 0 ns
Wall time: 995 µs
Iterative execution time: 0.0
CPU times: total: 0 ns
Wall time: 0 ns


**NumPy result:** [ 3  4 -1  6  5 -1  3 -1  4]

**Iterative result:** [3, 4, -1, 6, 5, -1, 3, -1, 4]

## Вправа 9
*Вводиться число n. Створити масив значень від n до 0.*

In [2]:   task_9() 

Out[2]: 10
| 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0 | 
|---|---|---|---|---|---|---|---|---|---|---|
      
### Код програми (виконання завдання першим та другим способами):

In [9]:
from IPython.display import display, Markdown

def task_9_numpy(n):
    start_time = time.time()
    np_arr = np.arange(n, -1, -1)
    end_time = time.time()
    print("NumPy execution time:", end_time - start_time)
    return np_arr

def task_9_iterative(n):
    start_time = time.time()
    arr_iterative = [i for i in range(n, -1, -1)]
    end_time = time.time()
    print("Iterative execution time:", end_time - start_time)
    return arr_iterative

n = int(input("Enter the number n: "))

# Виклик функцій та вивід результатів 
result_numpy = task_9_numpy(n)
result_iterative = task_9_iterative(n)

display(Markdown(f"**NumPy result:** {result_numpy}"))
display(Markdown(f"**Iterative result:** {result_iterative}"))

Enter the number n: 10
NumPy execution time: 0.001993894577026367
Iterative execution time: 0.0


**NumPy result:** [10  9  8  7  6  5  4  3  2  1  0]

**Iterative result:** [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

## Вправа 10
*Вводиться числа n i m. Створити масив випадкових значень n×m і обчислити мінімальне, максимальне значення, середнє та середньо квадратичне відхилення, округлене до 3 знаків після коми.*

In [2]:   task_10() 

Out[2]: 4   5

Мінімальне значення: 0.038 

Максимальне значення: 0.946 

Середнє значення: 0.593 

Дисперсія: 0.302

      
### Код програми (виконання завдання першим та другим способами):

In [10]:
import numpy as np
from IPython.display import display, Markdown
import timeit

def task_10_numpy(arr):
    start_time = timeit.default_timer()
    # Обчислення мінімального, максимального, середнього значень та середньо-квадратичного відхилення (1 спосіб)
    min_val = np.min(arr)
    max_val = np.max(arr)
    mean_val = np.mean(arr)
    std_val = np.std(arr)
    
    end_time = timeit.default_timer()
    elapsed_time = end_time - start_time
    
    return round(min_val, 3), round(max_val, 3), round(mean_val, 3), round(std_val, 3)

def task_10_iterative(arr):
    start_time = timeit.default_timer()
    # Обчислення мінімального, максимального, середнього значень та середньо-квадратичного відхилення (2 спосіб)
    min_val = min(arr.flatten())
    max_val = max(arr.flatten())
    mean_val = sum(arr.flatten()) / len(arr.flatten())
    std_val = (sum((x - mean_val) ** 2 for x in arr.flatten()) / len(arr.flatten())) ** 0.5
    
    end_time = timeit.default_timer()
    elapsed_time = end_time - start_time
    
    return round(min_val, 3), round(max_val, 3), round(mean_val, 3), round(std_val, 3)

n = int(input("Введіть кількість рядків (n): "))
m = int(input("Введіть кількість стовпців (m): "))

# Створення масиву випадкових значень n×m
random_array = np.random.rand(n, m)
display(Markdown("Масив випадкових значень n × m :"))
display(random_array)

# Використання timeit для точного вимірювання часу виконання
time_numpy = timeit.timeit(lambda: task_10_numpy(random_array), number=100)
time_iterative = timeit.timeit(lambda: task_10_iterative(random_array), number=100)

# Виклик функцій та вивід результатів
result_numpy = task_10_numpy(random_array)
result_iterative = task_10_iterative(random_array)

display(Markdown(f"**NumPy result:**\n"
                 f"Min: {result_numpy[0]}, Max: {result_numpy[1]}, "
                 f"Mean: {result_numpy[2]}, Root-mean-square deviation: {result_numpy[3]}, "
                 f"Execution Time: {time_numpy:.10f} seconds"))

display(Markdown(f"**Iterative result:**\n"
                 f"Min: {result_iterative[0]}, Max: {result_iterative[1]}, "
                 f"Mean: {result_iterative[2]}, Root-mean-square deviation: {result_iterative[3]}, "
                 f"Execution Time: {time_iterative:.10f} seconds"))

Введіть кількість рядків (n): 4
Введіть кількість стовпців (m): 5


Масив випадкових значень n × m :

array([[0.55114985, 0.51178561, 0.35213542, 0.66438347, 0.70458808],
       [0.18336528, 0.66632148, 0.71091847, 0.66427695, 0.44450272],
       [0.7709515 , 0.04553101, 0.0263019 , 0.39678467, 0.52311279],
       [0.07353894, 0.24877419, 0.93896896, 0.59783931, 0.13581304]])

**NumPy result:**
Min: 0.026, Max: 0.939, Mean: 0.461, Root-mean-square deviation: 0.261, Execution Time: 0.0165861000 seconds

**Iterative result:**
Min: 0.026, Max: 0.939, Mean: 0.461, Root-mean-square deviation: 0.261, Execution Time: 0.0117558000 seconds

## Вправа 12
*Створити масив одиниць розміром n×n та створити в ньому «рамку», що утворюється з 0.*

In [2]:   task_12() 

Out[2]: 4

| 0. | 0. | 0. | 0. |
|---|---|---|---|
| 0. | 1. | 1. | 0. |
| 0. | 1. | 1. | 0. | 
| 0. | 0. | 0. | 0. |
      
### Код програми (виконання завдання першим та другим способами):

In [11]:
import numpy as np
import pandas as pd
from IPython.display import display, Markdown
import timeit

def task_12_numpy(n):
    start_time = timeit.default_timer()
    # Створення масиву нулів розміром n×n
    arr = np.zeros((n, n), dtype=int)

    # Заміна внутрішньої «рамки» у масиві на 1
    arr[1:-1, 1:-1] = 1

    end_time = timeit.default_timer()
    elapsed_time = end_time - start_time
    
    return arr, elapsed_time

def task_12_iterative(n):
    start_time = timeit.default_timer()
    # Створення масиву нулів розміром n×n
    arr = np.zeros((n, n), dtype=int)

    # Заміна внутрішньої «рамки» у масиві на 1
    for i in range(1, n - 1):
        for j in range(1, n - 1):
            arr[i, j] = 1

    end_time = timeit.default_timer()
    elapsed_time = end_time - start_time
    
    return arr, elapsed_time

n = int(input("Введіть розмір масиву n: "))

# Виклик функцій та вивід результатів
result_numpy, time_numpy = task_12_numpy(n)
result_iterative, time_iterative = task_12_iterative(n)
display(Markdown("**NumPy result:**"))
display(pd.DataFrame(result_numpy))
display(Markdown(f"Execution Time: {time_numpy:.10f} seconds"))

display(Markdown("**Iterative result:**"))
display(pd.DataFrame(result_iterative))
display(Markdown(f"Execution Time: {time_iterative:.10f} seconds"))

Введіть розмір масиву n: 4


**NumPy result:**

0  1  2  3
0  0  0  0  0
1  0  1  1  0
2  0  1  1  0
3  0  0  0  0

Execution Time: 0.0000475000 seconds

**Iterative result:**

0  1  2  3
0  0  0  0  0
1  0  1  1  0
2  0  1  1  0
3  0  0  0  0

Execution Time: 0.0000141000 seconds

## Вправа 14
*Розмістити на полі 8×8 нулі та одиниці в шахматному порядку, використовуючи функцію numpy tile().*

In [2]:   task_14() 

Out[2]: 

| 0 | 1 | 0 | 1 | 0 | 1 | 0 | 1 | 
|---|---|---|---|---|---|---|---|
| 1 | 0 | 1 | 0 | 1 | 0 | 1 | 0 | 
| 0 | 1 | 0 | 1 | 0 | 1 | 0 | 1 | 
| 1 | 0 | 1 | 0 | 1 | 0 | 1 | 0 | 
| 0 | 1 | 0 | 1 | 0 | 1 | 0 | 1 |
| 1 | 0 | 1 | 0 | 1 | 0 | 1 | 0 | 
| 0 | 1 | 0 | 1 | 0 | 1 | 0 | 1 |
| 1 | 0 | 1 | 0 | 1 | 0 | 1 | 0 | 
      
### Код програми (виконання завдання першим та другим способами):

In [12]:
def task_14_numpy(n):
    start_time = timeit.default_timer()

    # Створення шахматної дошки за допомогою функції tile()
    chessboard = np.tile([[0, 1], [1, 0]], (n // 2, n // 2))

    end_time = timeit.default_timer()
    elapsed_time = end_time - start_time

    return chessboard, elapsed_time

def task_14_iterative(n):
    start_time = timeit.default_timer()

    # Створення шахматної дошки з допомогою циклів 
    chessboard = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(n):
            chessboard[i, j] = (i + j) % 2

    end_time = timeit.default_timer()
    elapsed_time = end_time - start_time

    return chessboard, elapsed_time

# Розмір шахматної дошки
n = 8

# Виклик функцій та вивід результатів
result_numpy, time_numpy = task_14_numpy(n)
result_iterative, time_iterative = task_14_iterative(n)
display(Markdown("**NumPy result:**"))
display(result_numpy)
display(Markdown(f"Execution Time (NumPy): {time_numpy:.10f} seconds"))

display(Markdown("**Iterative result:**"))
display(result_iterative)
display(Markdown(f"Execution Time (Iterative): {time_iterative:.10f} seconds"))

**NumPy result:**

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Execution Time (NumPy): 0.0044614000 seconds

**Iterative result:**

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

Execution Time (Iterative): 0.0000602000 seconds

## Вправа 15
*Заповнити парні стовпчикі матриці розміром n×n одиницями, а непарні – нулями.*

In [2]:   task_15() 

Out[2]:   5

| 0 | 1 | 0 | 1 | 0 | 
|---|---|---|---|---|
| 0 | 1 | 0 | 1 | 0 | 
| 0 | 1 | 0 | 1 | 0 | 
| 0 | 1 | 0 | 1 | 0 |  
| 0 | 1 | 0 | 1 | 0 |   
      
### Код програми (виконання завдання першим та другим способами):

In [13]:
def task_15_numpy(n):
    start_time = timeit.default_timer()

    # Створення матриці розміром n×n та заповнення парних стовпчиків одиницями, а непарних - нулями
    matrix = np.zeros((n, n), dtype=int)
    matrix[:, 1::2] = 1  # Починаючи з другого стовпчика, кожен другий стовпчик заповнюється одиницями

    end_time = timeit.default_timer()
    elapsed_time = end_time - start_time
    
    return matrix, elapsed_time

def task_15_iterative(n):
    start_time = timeit.default_timer()

    # Створення та заповнення матриці за допомогою функції np.zeros та циклів for
    matrix = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(1, n, 2):
            matrix[i, j] = 1

    end_time = timeit.default_timer()
    elapsed_time = end_time - start_time
    
    return matrix, elapsed_time

n = int(input("Введіть розмір матриці n: "))

# Виклик функцій та вивід результатів 
result_numpy, time_numpy = task_15_numpy(n)
result_iterative, time_iterative = task_15_iterative(n)
display(Markdown("**NumPy result:**"))
display(result_numpy)
display(Markdown(f"Execution Time (NumPy): {time_numpy:.10f} seconds"))

display(Markdown("**Iterative result:**"))
display(result_iterative)
display(Markdown(f"Execution Time (Iterative): {time_iterative:.10f} seconds"))

Введіть розмір матриці n: 5


**NumPy result:**

array([[0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0]])

Execution Time (NumPy): 0.0000432000 seconds

**Iterative result:**

array([[0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0]])

Execution Time (Iterative): 0.0000152000 seconds

## Вправа 21
*Ввести числа n і m. Згенерувати матрицю n×n випадкових цілих елементів з діапазону [0, m]. Замінити всі максимальні елементи цієї матриці на протилежні за знаком.*

In [2]:   task_21() 

Out[2]:   4  10

Початковий вектор: 
| 9 | 6 | 0 | 9 | 
|---|---|---|---|
| 4 | 3 | 7 | 9 | 
| 4 | 1 | 0 | 8 | 
| 5 | 5 | 4 | 8 |  

Змінений вектор: 
| -9 | 6 | 0 | -9 | 
|---|---|---|---|
| 4 | 3 | 7 | -9 | 
| 4 | 1 | 0 | 8 | 
| 5 | 5 | 4 | 8 |  
      
### Код програми (виконання завдання першим та другим способами):

In [14]:
import numpy as np
import timeit

def task_21_numpy(matrix):
    start_time = timeit.default_timer()

    # Знаходження максимального значення в матриці
    max_value = np.max(matrix)

    # Заміна всіх максимальних значень на протилежні за знаком
    matrix[matrix == max_value] *= -1

    end_time = timeit.default_timer()
    elapsed_time = end_time - start_time
    
    return matrix, elapsed_time

def task_21_iterative(matrix):
    start_time = timeit.default_timer()

    # Знаходження максимального значення в матриці
    max_value = max(max(row) for row in matrix)

    # Заміна всіх максимальних значень на протилежні за знаком
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            if matrix[i][j] == max_value:
                matrix[i][j] *= -1

    end_time = timeit.default_timer()
    elapsed_time = end_time - start_time
    
    return matrix, elapsed_time

n = int(input("Введіть розмір матриці n: "))
m = int(input("Введіть верхню межу діапазону m для генерації випадкових чисел: "))

# Створення матриці n×n випадкових цілих елементів з діапазону [0, m]
matrix = np.random.randint(0, m + 1, size=(n, n))

print("Початковий вектор:")
print(matrix)

# Виклик функцій та вивід результатів
result_numpy, time_numpy = task_21_numpy(matrix.copy())
result_iterative, time_iterative = task_21_iterative(matrix.copy())

# Вивід зміненого вектора та часу виконання
print("\nЗмінений вектор (NumPy):")
print(result_numpy)
print(f"Час виконання (NumPy): {time_numpy:.10f} секунд")

print("\nЗмінений вектор (Iterative):")
print(result_iterative)
print(f"Час виконання (Iterative): {time_iterative:.10f} секунд")

Введіть розмір матриці n: 4
Введіть верхню межу діапазону m для генерації випадкових чисел: 10
Початковий вектор:
[[ 1  8  5  6]
 [ 5  6  1  6]
 [ 5  0  5  6]
 [ 4  8 10  9]]

Змінений вектор (NumPy):
[[  1   8   5   6]
 [  5   6   1   6]
 [  5   0   5   6]
 [  4   8 -10   9]]
Час виконання (NumPy): 0.0003332000 секунд

Змінений вектор (Iterative):
[[  1   8   5   6]
 [  5   6   1   6]
 [  5   0   5   6]
 [  4   8 -10   9]]
Час виконання (Iterative): 0.0000560000 секунд


# Постанова Задачі № 2
*Розв’язати систему алгебраїчних рівнянь за допомогою формул Крамера і виконати перевірку за допомогою:*
* матричного множення; 
* оберненої матриці; 
* функції numpy.linalg.solve(). 

*Порівняти всі рішення за допомогою функції numpy.allclose().*

**Індивідуальне завдання (згідно варіанту № 5):**
\begin{align*}
x_1 + 3x_2 + 5x_3 + 7x_4 &= 12 \\
3x_1 + 5x_2 + 7x_3 + x_4 &= 0 \\
5x_1 + 7x_2 + x_3 + 3x_4 &= 4 \\
7x_1 + x_2 + 3x_3 + 5x_4 &= 16 \\
\end{align*}

In [15]:
import numpy as np

# Коефіцієнти системи рівнянь
A = np.array([[1, 3, 5, 7],
              [3, 5, 7, 1],
              [5, 7, 1, 3],
              [7, 1, 3, 5]])

# Вільні члени
B = np.array([12, 0, 4, 16])

# Розв'язок за допомогою формули Крамера
det_A = np.linalg.det(A)
results_kramer = np.array([round(np.linalg.det(np.column_stack((A[:, :i], B, A[:, i+1:])))/det_A) for i in range(A.shape[1])])

# Перевірка розв'язку за допомогою матричного множення
check_matrix_multiply = np.dot(A, results_kramer)

# Перевірка розв'язку за допомогою оберненої матриці
A_inv = np.linalg.inv(A)
check_inverse_matrix = np.dot(A_inv, B)
check_inverse_matrix_rounded = np.round(check_inverse_matrix).astype(int)

# Перевірка розв'язку за допомогою numpy.linalg.solve()
check_solve = np.linalg.solve(A, B)
check_solve_rounded = np.round(check_solve).astype(int)

print("Розв'язок за допомогою формули Крамера:", results_kramer)
print("\nПеревірка за допомогою матричного множення (A * X):", check_matrix_multiply)
print("\nПеревірка за допомогою оберненої матриці (A_inv * B):", check_inverse_matrix_rounded)
print("\nПеревірка за допомогою numpy.linalg.solve():", check_solve_rounded)

# Порівняння всіх рішень за допомогою numpy.allclose()
result_kramer = np.allclose(results_kramer, B)
result_matrix_multiply = np.allclose(check_matrix_multiply, B)
result_inverse_matrix = np.allclose(check_inverse_matrix, B)
result_solve = np.allclose(check_solve, B)
print("\nПорівняння за допомогою numpy.allclose() - Формула Крамера:", result_kramer)
print("Порівняння за допомогою numpy.allclose() - Матричне множення:", result_matrix_multiply)
print("Порівняння за допомогою numpy.allclose() - Обернена матриця:", result_inverse_matrix)
print("Порівняння за допомогою numpy.allclose() - numpy.linalg.solve():", result_solve)

Розв'язок за допомогою формули Крамера: [ 1 -1  0  2]

Перевірка за допомогою матричного множення (A * X): [12  0  4 16]

Перевірка за допомогою оберненої матриці (A_inv * B): [ 1 -1  0  2]

Перевірка за допомогою numpy.linalg.solve(): [ 1 -1  0  2]

Порівняння за допомогою numpy.allclose() - Формула Крамера: False
Порівняння за допомогою numpy.allclose() - Матричне множення: True
Порівняння за допомогою numpy.allclose() - Обернена матриця: False
Порівняння за допомогою numpy.allclose() - numpy.linalg.solve(): False


# Постанова Задачі № 3
*Обчислити значення матричного виразу:*
* з використанням універсальних функцій бібліотеки NumPy;
* за допомогою ітеративних конструкцій (з використанням циклів, спискових включень тощо).

*Для обох випадків підрахувати час виконання скрипту та зробити висновок.*

*Порівняти всі рішення за допомогою функції numpy.allclose().*

**Індивідуальне завдання (згідно варіанту № 5):**


(A - B^2)(2A + B),

де
A = \begin{pmatrix}
5 & 2 & 0 \\
10 & 4 & 1 \\
7 & 3 & 2 \\
\end{pmatrix}

та
B = \begin{pmatrix}
3 & 6 & -1 \\
-1 & -2 & 0 \\
2 & 1 & 3 \\
\end{pmatrix}

### Код програми (виконання завдання першим та другим способами):

In [16]:
import numpy as np
import time

A = np.array([[5, 2, 0], [10, 4, 1], [7, 3, 2]])
B = np.array([[3, 6, -1], [-1, -2, 0], [2, 1, 3]])

start_time = time.time()

B_squared = np.matmul(B, B)
A_minus_B_squared = np.subtract(A, B_squared)
two_A = np.multiply(2, A)
two_A_plus_B = np.add(two_A, B)
result = np.matmul(A_minus_B_squared, two_A_plus_B)

end_time = time.time()
print("Час виконання з використанням NumPy: ", end_time - start_time, "секунд")

start_time = time.time()

# обчислення B^2
B_squared = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for i in range(len(B)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            B_squared[i][j] += B[i][k] * B[k][j]

# обчислення A - B^2
A_minus_B_squared = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for i in range(len(A)):
    for j in range(len(A[0])):
        A_minus_B_squared[i][j] = A[i][j] - B_squared[i][j]

# обчислення 2A + B
two_A_plus_B = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for i in range(len(A)):
    for j in range(len(A[0])):
        two_A_plus_B[i][j] = 2 * A[i][j] + B[i][j]

# обчислення (A - B^2) * (2A + B)
result2 = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
for i in range(len(A_minus_B_squared)):
    for j in range(len(two_A_plus_B[0])):
        for k in range(len(two_A_plus_B)):
            result2[i][j] += A_minus_B_squared[i][k] * two_A_plus_B[k][j]

end_time = time.time()
print("Час виконання з використанням циклів: ", end_time - start_time, "секунд")

print("Результат з використанням NumPy:")
print(result)
print("Результат з використанням циклів:")
print(result2)

print("Чи співпадають результати?", np.allclose(result, result2))

Час виконання з використанням NumPy:  0.00099945068359375 секунд
Час виконання з використанням циклів:  0.0009980201721191406 секунд
Результат з використанням NumPy:
[[  91   64   32]
 [ 257  146    1]
 [-322 -135  -51]]
Результат з використанням циклів:
[[91, 64, 32], [257, 146, 1], [-322, -135, -51]]
Чи співпадають результати? True
